version: "3"
services:
    frontend:
        build: ./app/starwars/.
        image: sw-frontend:latest
        ports:
            - 80:80
        networks:
            - overlay
        depends_on:
            - backend
    backend:
        build:
            context: ./server/resupply-stops/
            dockerfile: ./ResupplyStops/Dockerfile
        image: sw-backend:latest
        ports:
            - 8080:80
        networks:
            - overlay
networks:
  overlay: